name: ecomgames
services:
  angular-ssr:
    container_name: ecomgames
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOST=0.0.0.0
    restart: always